print("Welcome to the first lab of 2025's AI Applications!")
name = input("What is your name? ")
print("Hello " + name +", it's nice to have you here!")
language = input("What is your favorite programming language to use? ")
print("Good choice " + name + ", " + language + " is fun to use!")